import React from 'react';
import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import type { PayrollCalculationResult } from '@repo/payroll-rules';

export interface PayrollCalculatorDocumentProps {
  result: PayrollCalculationResult;
}

function formatNumber(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount);
}

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, fontFamily: 'Helvetica' },
  title: { fontSize: 16, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#555', marginBottom: 16 },
  section: { marginBottom: 16 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
    paddingBottom: 4,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
    borderBottomWidth: 0.5,
    borderBottomColor: '#ccc',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 6,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: '#000',
    fontWeight: 700,
    fontSize: 12,
  },
  label: { color: '#333' },
  amount: { textAlign: 'right' },
  disclaimer: { marginTop: 24, fontSize: 8, color: '#777' },
});

export function PayrollCalculatorDocument({
  result,
}: PayrollCalculatorDocumentProps) {
  const fmt = (amount: number) => `${formatNumber(amount)} ${result.currency}`;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Payroll Estimate</Text>
        <Text style={styles.subtitle}>
          {result.countryCode} — rule version {result.ruleVersion}
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Earnings</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Basic Salary</Text>
            <Text style={styles.amount}>
              {fmt(result.earnings.basicSalary)}
            </Text>
          </View>
          {Object.entries(result.earnings.allowanceBreakdown).map(
            ([key, value]) => (
              <View style={styles.row} key={key}>
                <Text style={styles.label}>{key}</Text>
                <Text style={styles.amount}>{fmt(value)}</Text>
              </View>
            ),
          )}
          <View style={styles.totalRow}>
            <Text>Gross Pay</Text>
            <Text style={styles.amount}>{fmt(result.grossPay)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Statutory Deductions</Text>
          {result.statutoryDeductions.map((deduction) => (
            <View style={styles.row} key={deduction.code}>
              <Text style={styles.label}>{deduction.label}</Text>
              <Text style={styles.amount}>{fmt(deduction.employeeAmount)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Tax</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Taxable Income</Text>
            <Text style={styles.amount}>{fmt(result.tax.taxableIncome)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Gross Tax</Text>
            <Text style={styles.amount}>{fmt(result.tax.grossTax)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Relief</Text>
            <Text style={styles.amount}>-{fmt(result.tax.relief)}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text>Net Tax</Text>
            <Text style={styles.amount}>{fmt(result.tax.netTax)}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <View style={styles.totalRow}>
            <Text>Net Pay</Text>
            <Text style={styles.amount}>{fmt(result.netPay)}</Text>
          </View>
        </View>

        <Text style={styles.disclaimer}>
          This is an illustrative estimate generated by the PayFlow Africa
          payroll calculator. It is not a payslip and does not account for
          company-specific salary structures.
        </Text>
      </Page>
    </Document>
  );
}
